title: Virtual Atom
author: Tom Delame
email: admin@virtual-atom.com
description: >
  Hi, I'm Tom Delame! I am a R&D software engineer in Computer Graphics in Paris area. 
  I work in python and C++ on an intuitive and efficient professional 3D animation software.
  I also code game AI for fun.


twitter_username: AtomDelame
github_username:  tdelame
